spring.datasource.url=jdbc:postgresql://localhost:5433/loja_virtual_3m
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


#Ações do JPA
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/loja3m


#uploads
spring.servlet.multipart.max-file-size= 10000KB
spring.servlet.multipart.max-request-size= 10000KB
spring.servlet.multipart.enabled=true


#compressao
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
server.http2.enabled=true



#acentos
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.http.encoding.force-request=true
spring.http.encoding.force-response=true



#pool de conexoes

#
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

#numero maximo de milesegundos que um cliente guardará por uma conexão
spring.datasource.hikari.connection-timeout=20000

#numero minimo de conexoes inativas mantids pelo HirakiCP em um conjunto de conexoes
spring.datasource.hikari.minimum-idle=5

# Numero maximo de conexoes que o seu app pode abrir ao mesmo tempo (10 a 20 é mais que suficiente)
spring.datasource.hikari.maximum-pool-size=20

#tempo ociosos para conexao
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.pool-name=PoolHikari
spring.datasource.dbcp2.pool-prepared-statements=true
spring.datasource.dbcp2.max-open-prepared-statements=550

#salvando dados no banco automaticamente
## Salvando dados no banco automaticamente (Deixe como true para salvar seus testes do Postman de primeira!)
spring.datasource.hikari.auto-commit=true


#server.servlet.session.timeout=240m
spring.transaction.rollback-on-commit-failure=true
spring.jpa.properties.hibernate.jdbc.batch_size=4
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
server.tomcat.max-connections = 50000
server.tomcat.min-spare-threads=1000
spring.session.jdbc.cleanup-cron = 0 0 4 * * *


spring.mvc.static-path-pattern=/resoures/static/**





